# Generated by Django 4.0.4 on 2022-05-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.IntegerField()),
                ('description', models.CharField(max_length=10)),
            ],
        ),
    ]
